resetprop -n ro.vendor.thermalspace.backlight.support 1
resetprop -n ro.boottime.thermald 0
resetprop -n ro.boottime.thermal_manager 0 
resetprop -n ro.boottime.thermald 0 
resetprop -n ro.boottime.thermalloadalgod 0
resetprop -n ro.boottime.vendor.thermal-hal-2-0.mtk 0
resetprop -n ro.dar.thermal_core.support 0
resetprop -n ro.vendor.mtk_thermal_2_0 0
resetprop -n ro.vendor.thermalspace.backlight.support 1
resetprop -n ro.vendor.tran.hbm.thermal.temp.clr 99999
resetprop -n ro.vendor.tran.hbm.thermal.temp.trig 99999